= LTTng Scope (Alpha Version)

image:https://travis-ci.org/lttng/lttng-scope.svg?branch=master["Build Status", link="https://travis-ci.org/lttng/lttng-scope"]
image:https://scan.coverity.com/projects/12046/badge.svg["Coverity Scan Build Status", link="https://scan.coverity.com/projects/lttng-scope"]

_**LTTng Scope**_ is a trace viewer and analyzer for
http://diamon.org/ctf/[CTF] traces, with a focus on
https://lttng.org/[LTTng] kernel and user space traces.

LTTng Scope supports Windows, macOS, and Linux. The source code is
available under the https://www.eclipse.org/legal/epl-v10.html[Eclipse
Public License].

NOTE: LTTng Scope is currently under heavy development. You should not be
using it for anything serious, unless you know what you are doing!

== Requirements

The following items are required to run LTTng Scope:

* Java 8
* JavaFX

If you use Oracle's JVM, JavaFX is included. If you use OpenJDK, you might need
to install OpenJFX separately. On Debian/Ubuntu, it is part of the _openjfx_
package.


== Build from source

You need http://maven.apache.org[Maven] version 3.3 or later to build
this project from source.

To build LTTng Scope from source:

* From the project's root directory, run:
+
--
[role="term"]
----
mvn clean install
----
--

To build LTTng Scope from source and run the unit tests:

* From the project's root directory, run:
+
--
[role="term"]
----
mvn clean install -Dmaven.test.skip=false
----
--

Maven outputs the platform-specific application packages in the
`releng/org.lttng.scope.rcp.product/target/products` directory.


== Relation to Trace Compass

LTTng Scope is based on some parts of the Trace Compass source code. However
it is meant to be a separate project with different design goals. While
Trace Compass aims to support any analysis for any trace type,
LTTng Scope aims to:

* Focus on CTF/LTTng use cases
* Streamline the user experience
* Clearly separate layers (trace reading, analysis, UI)

Trace Compass is closely tied to the Eclipse platform. Because of this,
LTTng Scope also makes use of the Eclipse RCP framework initially, but that
is not a design requirement and could change in the future. Running analyses
on the command-line (in CI, etc.) with text-based output is also within
the realm of possibilities.


== User documentation

Not available yet.
